module.exports = {
	semi: true,
	useTabs: true,
	printWidth: 120,
	singleQuote: true,
	trailingComma: 'all',
	insertPragma: false,
	arrowParens: 'avoid',
	requirePragma: false,
	bracketSpacing: true,
	proseWrap: 'preserve',
	bracketSameLine: true,
	quoteProps: 'as-needed',
	astroAllowShorthand: true,
	htmlWhitespaceSensitivity: 'css',
	embeddedLanguageFormatting: 'auto',
	overrides: [{ files: '*.astro', options: { parser: 'astro' } }],
	plugins: ['prettier-plugin-astro', 'prettier-plugin-tailwindcss'],
};
